### ISSUE TITLE
When following the tutorial you have put in the readme the taskId is never set

### ISSUE THREAD

**Issue by wolfej94** [levibostian/Wendy-iOS#37]
At the point in the view when I am creating the pending task and adding it to Wendy my app crashes around this line 

`WendyConfig.addTaskStatusListenerForTask(task.taskId!, listener: self)`

Because the taskId is never being set when the 'CreateGroceryListItemPendingTask' is initialised.

**Comment by levibostian** [comment]
Hello! 

I am assuming you are talking about this code in the readme:

![2020-08-05 at 9 45 AM](https://user-images.githubusercontent.com/2041082/89427110-7f10ca00-d700-11ea-989b-654106c93bf1.png)

The readme has a typo in it I think. Replace `task.taskId!` with `pendingTaskId`. The id given back to you when you call `Wendy.shared.addTask`

**Comment by wolfej94** [comment]
Excellent, I actually tried this a couple of hours before you commented, but clarification from the dev let's me know I'm on the right track! Thanks
