### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by swiatrzyk** [levibostian/Wendy-iOS#45]
Would be nice to have SPM as an option

**Comment by levibostian** [comment]
Thanks for the suggestion, @swiatrzyk. I absolutely agree with you. 

I have limited availability at this time so my focus is elsewhere unfortunately. Contributions are welcome to add SPM support to the lib. It would be very quick for me to add, but I don't have the availability to test it to make sure it's working.

**Comment by levibostian** [comment]
`Package.swift` on `main` branch ready to use.
